spring:
  application:
    name: chat-app
  profiles:
    active: dev
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      database: ${spring.data.redis.database}
      connect-timeout: ${spring.data.redis.connect-timeout}
      timeout: ${spring.data.redis.timeout}
  alioss:
    endpoint: ${spring.alioss.endpoint}
    access-key-id: ${spring.alioss.access-key-id}
    access-key-secret: ${spring.alioss.access-key-secret}
    bucket-name: ${spring.alioss.bucket-name}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB   # 整个请求最大限制（包含所有文件和表单数据）
langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen3-vl-plus-2025-12-19
      log-requests: true
      log-responses: true
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: text-embedding-v4 # 推荐使用 v3
      log-requests: true
      log-responses: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator  # 建议显式指定（默认就是 /actuator）
    tags:
      application: ${spring.application.name}

# 新增：PostgreSQL 向量数据库配置 (仅供 RAG 使用)
rag:
  postgres:
    host: localhost
    port: 5432
    database: atrl_chat
    user: postgres
    password: 123456
    table: conversation_memories
    dimension: 1024  # 必须与你创建表时的维度一致

logging:
  level:
    dev.langchain4j: debug

server:
  port: 8085


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #log
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #camel
    map-underscore-to-camel-case: true

chatapp:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${chatapp.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: ${chatapp.jwt.admin-ttl}
    # 设置前端传递过来的令牌名称
    admin-token-name: ${chatapp.jwt.admin-token-name}
    user-secret-key: ${chatapp.jwt.user-secret-key}
    user-ttl: ${chatapp.jwt.user-ttl}
    user-token-name: ${chatapp.jwt.user-token-name}
  netty:
    websocket:
      enabled: true
      host: 0.0.0.0
      port: 8090
      path: /ws/group
      max-content-length: 65536


