-- Canonical PostgreSQL schema for chat-app
-- This script initializes the primary relational tables and supporting indexes.
-- RAG uses PostgreSQL as well; pgvector is enabled here so the embedding store can
-- create or use its vector tables in the same database.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    avatar_url VARCHAR(255) DEFAULT 'https://sky-wanzimo.oss-cn-beijing.aliyuncs.com/character_avatars/49_1757839782483.jpg',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    CONSTRAINT uk_app_user_username UNIQUE (username),
    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_name VARCHAR(64) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(128),
    phone VARCHAR(32),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    CONSTRAINT uk_admin_name UNIQUE (admin_name),
    CONSTRAINT uk_admin_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS app_character (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    image VARCHAR(255),
    is_public SMALLINT NOT NULL DEFAULT 0 CHECK (is_public IN (0, 1)),
    appearance TEXT,
    background TEXT,
    personality TEXT,
    classic_lines TEXT,
    user_id BIGINT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    CONSTRAINT fk_character_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chat_group (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    avatar_url VARCHAR(255) DEFAULT 'https://sky-wanzimo.oss-cn-beijing.aliyuncs.com/group_default.jpg',
    creator_id BIGINT NOT NULL,
    character_id BIGINT,
    description VARCHAR(500),
    max_members INTEGER NOT NULL DEFAULT 500,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    CONSTRAINT fk_group_creator
        FOREIGN KEY (creator_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_character
        FOREIGN KEY (character_id) REFERENCES app_character (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS chat_group_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'MEMBER' CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER')),
    nickname VARCHAR(50),
    join_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_read_time TIMESTAMP,
    is_muted SMALLINT NOT NULL DEFAULT 0 CHECK (is_muted IN (0, 1)),
    is_deleted SMALLINT NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    CONSTRAINT uk_group_user UNIQUE (group_id, user_id),
    CONSTRAINT fk_member_group
        FOREIGN KEY (group_id) REFERENCES chat_group (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chat_group_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    sender_id BIGINT,
    sender_type VARCHAR(16) NOT NULL DEFAULT 'USER' CHECK (sender_type IN ('USER', 'AI')),
    character_id BIGINT,
    content TEXT NOT NULL,
    content_type VARCHAR(20) NOT NULL DEFAULT 'text',
    image_url VARCHAR(255),
    reply_to_id BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    CONSTRAINT fk_message_group
        FOREIGN KEY (group_id) REFERENCES chat_group (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_sender
        FOREIGN KEY (sender_id) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_message_character
        FOREIGN KEY (character_id) REFERENCES app_character (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS user_follow_character (
    follow_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    character_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status SMALLINT NOT NULL DEFAULT 1 CHECK (status IN (0, 1)),
    CONSTRAINT uk_user_character UNIQUE (user_id, character_id),
    CONSTRAINT fk_ufc_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_ufc_character
        FOREIGN KEY (character_id) REFERENCES app_character (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS private_chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id VARCHAR(128) NOT NULL,
    user_id BIGINT NOT NULL,
    character_id BIGINT NOT NULL,
    sender_type VARCHAR(16) NOT NULL CHECK (sender_type IN ('USER', 'AI')),
    content TEXT,
    image_url VARCHAR(512),
    is_deleted SMALLINT NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS memory_index (
    memory_id VARCHAR(128) NOT NULL,
    memory_key VARCHAR(128) NOT NULL,
    embedding_id VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (memory_id, memory_key)
);

CREATE TABLE IF NOT EXISTS ai_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    character_id VARCHAR(64) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    memory_id VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    total_tokens INTEGER NOT NULL DEFAULT 0,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    request_ts TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_app_user_phone ON app_user (phone);
CREATE INDEX IF NOT EXISTS idx_app_character_name ON app_character (name);
CREATE INDEX IF NOT EXISTS idx_app_character_user_id ON app_character (user_id);
CREATE INDEX IF NOT EXISTS idx_app_character_is_public ON app_character (is_public);
CREATE INDEX IF NOT EXISTS idx_chat_group_creator_id ON chat_group (creator_id);
CREATE INDEX IF NOT EXISTS idx_chat_group_character_id ON chat_group (character_id);
CREATE INDEX IF NOT EXISTS idx_chat_group_create_time ON chat_group (create_time);
CREATE INDEX IF NOT EXISTS idx_chat_group_member_group_id ON chat_group_member (group_id);
CREATE INDEX IF NOT EXISTS idx_chat_group_member_user_id ON chat_group_member (user_id);
CREATE INDEX IF NOT EXISTS idx_chat_group_message_group_time ON chat_group_message (group_id, create_time);
CREATE INDEX IF NOT EXISTS idx_chat_group_message_sender_id ON chat_group_message (sender_id);
CREATE INDEX IF NOT EXISTS idx_chat_group_message_character_id ON chat_group_message (character_id);
CREATE INDEX IF NOT EXISTS idx_private_chat_message_memory_id ON private_chat_message (memory_id);
CREATE INDEX IF NOT EXISTS idx_private_chat_message_create_time ON private_chat_message (create_time);
CREATE INDEX IF NOT EXISTS idx_memory_index_embedding_id ON memory_index (embedding_id);
CREATE INDEX IF NOT EXISTS idx_ai_call_log_user_status_time_tokens ON ai_call_log (user_id, status, request_ts, total_tokens);
CREATE INDEX IF NOT EXISTS idx_ai_call_log_character_time ON ai_call_log (character_id, request_ts);
CREATE INDEX IF NOT EXISTS idx_ai_call_log_memory ON ai_call_log (memory_id);
CREATE INDEX IF NOT EXISTS idx_ai_call_log_created_at ON ai_call_log (created_at);

-- Sequence repair examples for imported data:
-- SELECT setval(pg_get_serial_sequence('admin', 'id'), COALESCE(MAX(id), 1), true) FROM admin;
-- SELECT setval(pg_get_serial_sequence('app_character', 'id'), COALESCE(MAX(id), 1), true) FROM app_character;
-- SELECT setval(pg_get_serial_sequence('chat_group_member', 'id'), COALESCE(MAX(id), 1), true) FROM chat_group_member;
-- SELECT setval(pg_get_serial_sequence('chat_group_message', 'id'), COALESCE(MAX(id), 1), true) FROM chat_group_message;
-- SELECT setval(pg_get_serial_sequence('private_chat_message', 'id'), COALESCE(MAX(id), 1), true) FROM private_chat_message;
-- SELECT setval(pg_get_serial_sequence('ai_call_log', 'id'), COALESCE(MAX(id), 1), true) FROM ai_call_log;
